source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

ruby '2.3.1'
gem 'rails', '5.1.5'

# Rails defaults
gem 'sqlite3'
gem 'puma', '~> 3.7'
gem 'sass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'byebug'
gem 'web-console', '>= 3.3.0'
gem 'spring'

# learn-rails
gem 'foundation-rails'
gem 'gibbon'
gem 'high_voltage'
gem 'simple_form'
group :development do
 gem 'better_errors'
 gem 'rails_layout'

end
